### ISSUE TITLE
Migración de datos para modulo de producción académica

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_crud#18]

**Comment by CrissUD** [comment]
# Prueba local de migración 

Se realiza una prueba local de migración local para actualizar la estructura y las inserciones de la base de datos de **producción académica**, para esto se crea un nuevo documento sql que contiene todas las nuevas características de la estructura de la base de datos y posibles modificaciones de tablas existentes y además se actualiza el archivo sql del manejo de inserciones para insertar todos los elementos detallados en [este documento](https://docs.google.com/spreadsheets/d/1Ts3G6Q3DDV2P5cWz2X0zzWESF_F8JdndDrqjJkdBZ6E/edit?usp=sharing)

El resultado de la migración local muestra un éxito en la actualización de la estructura de la base de datos y en la inserción de cada una de las tablas paramétricas

![resultado](https://user-images.githubusercontent.com/44172561/99024661-0c03c480-2535-11eb-90a2-68bacf7f2528.png)


Los cambios a mas detalle pueden verse en el siguiente pullRequest
#21

**Comment by fabianbarreto02** [comment]
Falta revisar las etiquetas faltantes

**Comment by fabianbarreto02** [comment]
Se da por finalizada
