### ISSUE TITLE
Modificación Api producción académica

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_crud#19]

**Comment by Camiloqui** [comment]
inicialmente se realiza las migraciones de datos con base al modelo de datos aceptado por DBA, la ultima version de la base de datos esta en el siguiente link [Ver](https://github.com/udistrital/produccion_academica_cliente/issues/19)
Teniendo en cuenta el ultimo modelo de datos, se hacen las migraciones, luego se monta los controladores de cada tabla dentro de la base de datos:
![image](https://user-images.githubusercontent.com/19983790/99468087-c4eb4a00-290d-11eb-9f00-462bb55972f2.png)
Podemos evidenciar que salieron varios controladores, 1 por cada tabla, en cada controlador es donde mostramos la accion de los metodos puestos, dichos controladores traen metodos tipo CRUD donde son metodos llamados POST, GET, UPTADE, DELETE, la gran mayoria quedan de la siguiente manera:
![image](https://user-images.githubusercontent.com/19983790/99468408-83a76a00-290e-11eb-830a-b50547b74147.png)
Luego creamos los modelos de datos de cada tabla, una por cada tabla: 
![image](https://user-images.githubusercontent.com/19983790/99468443-9752d080-290e-11eb-87f4-947515a255bc.png) El modelo es la informacion que se va a subir o actualizar en la base de datos, donde estan los campos correspondientes a los atributos dentro del modelo de datos: como se muestra en el ejemplo
![image](https://user-images.githubusercontent.com/19983790/99468517-c79a6f00-290e-11eb-8659-eb232cd1da41.png)
tambien hace el llamado de los metodos que se crearon en los controladores, luego se crean las rutas de cada tabla: 
![image](https://user-images.githubusercontent.com/19983790/99469310-6bd0e580-2910-11eb-9820-9a2bdf7acf14.png)
Como cada tabla tiene varios metodos (5 por tabla) toca crear cada ruta por metodo creado, para que pueda ser llamado, luego creamos las rutas de los controladores:
![image](https://user-images.githubusercontent.com/19983790/99469401-9b7fed80-2910-11eb-9ed9-9559d510a15e.png)
ahi simplemente hacemos el llamado, para que se pueda buscar cada peticion dentro de la url: ejemplo si hacemos el llamado de alguna tabla en peticion tipo GET: nos deberia dar el contenido de dicha tabla ejemplo sacaremos la informacion de la tabla tipo_produccion

![image](https://user-images.githubusercontent.com/19983790/99469706-53ad9600-2911-11eb-90b0-36ca4cb345cf.png)
Aqui se evidencia que llama los datos de la tabla dentro de la base de datos. Esto igual sucede en cada tabla creada en base al modelo de datos

**Comment by Camiloqui** [comment]
Con esto se puede mandar a verificación que la api produccion_academica_crud haya sido correctamente modificada, y pueda ser usada dentro del cliente que se esta creando y no tenga conflictos con las peticiones del crud

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se espera cerrar la issue en el sprint
