### ISSUE TITLE
Modificación de api crud de producción academica con nuevo modelo

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/produccion_academica_crud#2]
Modificación del api teniendo en cuenta el nuevo modelo.

**Comment by JuanPiedrahita** [comment]
Se crean [nueva versión del modelo](https://drive.google.com/drive/folders/1r4OODJ_QxX0JxruCOmA-BM_146ZteuU8?usp=sharing) teniendo en cuenta algunos ajustes generales.

**Comment by JuanPiedrahita** [comment]
Dockerización de proyecto para desarrollo https://github.com/udistrital/produccion_academica_crud/commit/8240f5cd02eef24152c59c99a252beb63ecab7c9.

**Comment by JuanPiedrahita** [comment]
Modificación del readme según dockerización https://github.com/udistrital/produccion_academica_crud/commit/386b2f00c7b7fab906f1b2eabcd68f346c598ab7.

**Comment by JuanPiedrahita** [comment]
Actualización de proyecto teniendo en cuenta el nuemo modelo https://github.com/udistrital/produccion_academica_crud/commit/5059e38032ac8b36164c05ca05dc7e61f7e2e4f5.

**Comment by JuanPiedrahita** [comment]
Aplicando relatedSel y auto para modelos https://github.com/udistrital/produccion_academica_crud/commit/f03fb7358dd9b3961ded224dc4008236d723649a.

**Comment by JuanPiedrahita** [comment]
Aplicando script refactoring para respuestas json del api https://github.com/udistrital/produccion_academica_crud/commit/f30c7ea00115f0752db05a01d8aef6dc26e70d2e.

**Comment by mafeave** [comment]
Se revisan los commits realizados, tener en cuenta las siguientes observaciones:
- ajustar auto de modelo de tipo_produccion.go
- agregar las variables de configuración para la conexión a la base de datos

**Comment by JuanPiedrahita** [comment]
Se atienden las observaciones  https://github.com/udistrital/produccion_academica_crud/commit/069fa0bb0bccca4ca83d309316bd0a8533ee0c27.

**Comment by mafeave** [comment]
Verificados los ajustes, se da por finalizada la tarea.
