### ISSUE TITLE
Modificación de crud para manejar de transaciones de nuevo modelo de producción academica

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/produccion_academica_crud#3]
Modificación del crud teniendo en cuenta el nuevo modelo de producción academica.

**Comment by JuanPiedrahita** [comment]
Docker para desarrollo
https://github.com/udistrital/produccion_academica_crud/commit/8240f5cd02eef24152c59c99a252beb63ecab7c9
https://github.com/udistrital/produccion_academica_crud/commit/386b2f00c7b7fab906f1b2eabcd68f346c598ab7

**Comment by JuanPiedrahita** [comment]
Se regenera api con nuevo modelo
https://github.com/udistrital/produccion_academica_crud/commit/5059e38032ac8b36164c05ca05dc7e61f7e2e4f5

**Comment by JuanPiedrahita** [comment]
Se aplican estandares de la oas
https://github.com/udistrital/produccion_academica_crud/commit/f03fb7358dd9b3961ded224dc4008236d723649a
https://github.com/udistrital/produccion_academica_crud/commit/f30c7ea00115f0752db05a01d8aef6dc26e70d2e
https://github.com/udistrital/produccion_academica_crud/commit/ca7be07d60db0c33a3bd3ed2853f81f02ba240eb
https://github.com/udistrital/produccion_academica_crud/commit/069fa0bb0bccca4ca83d309316bd0a8533ee0c27
https://github.com/udistrital/produccion_academica_crud/commit/3fb61b232ddc9d86ecb2b6878bf7936d469c6ef2

**Comment by JuanPiedrahita** [comment]
Registrando producciones academicas
https://github.com/udistrital/produccion_academica_crud/commit/aaefb645d83d6092ac287840d59ff8902db15164

**Comment by JuanPiedrahita** [comment]
Quitando producciones academicas
https://github.com/udistrital/produccion_academica_crud/commit/c22c41616ba724da66d23a0f7cc1693f71070ede

**Comment by JuanPiedrahita** [comment]
Listando producciones
https://github.com/udistrital/produccion_academica_crud/commit/83cd3667d4aa6e23f47102c0218cf014bca6f43a

**Comment by JuanPiedrahita** [comment]
Borrando producciones
https://github.com/udistrital/produccion_academica_crud/commit/ed20b493adea9275e0ca17f337ff0f3b2b101b47

**Comment by JuanPiedrahita** [comment]
Haciendo update de producciones
https://github.com/udistrital/produccion_academica_crud/commit/3f912f38c3bbbb9a1a429a4ce24e8b22da2b7eb9
https://github.com/udistrital/produccion_academica_crud/commit/a10d6cdc63f65bc3ca842157b0258811d24abf02
https://github.com/udistrital/produccion_academica_crud/commit/745a09cc8000d5273a5471824da28cf2e264ea8c

**Comment by JuanPiedrahita** [comment]
Inserts básicos de producción y ejemplos para la creación de formularios con campos de la base:
https://drive.google.com/file/d/13lY-fQLvpXioLqpHgk8XE1DNNrkdfkrB/view?usp=sharing

**Comment by mafeave** [comment]
Se verifican los commits del desarrollo realizado, se envía a Planestic para verificación de la funcionalidad.
