### ISSUE TITLE
realizar ajustes sobre la rama feature/integracion master para desplegar en rama propia de planestic

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/produccion_academica_crud#45]
se requiere realizar los ajustes ya socializados para que los pasos de drone se ejecuten exitosamente, pero en este caso se usara [la plantilla de drone para la rama personalizada de planestic](https://github.com/udistrital/financiera_documentacion/issues/210) .

adicionalmente se requiere eliminar la carpeta `.scannerwork`

**Comment by jevilla94** [comment]
@BOTOOM @jevilla94 @miguerpe @neconoe @planesticud

Cordial saludo se realizaron los ajustes de rutas para comunicación udistrital y modificación de archivo drone.yml

https://github.com/udistrital/produccion_academica_crud/commit/9eadb7b4c6d542f7a0d87fa24fa6437ad0664ae4
